folks: Use build-options instead of config-opts to force libdir
Fixes the following build error:

    ERROR: Got argument libdir as both -Dlibdir and --libdir. Pick one.